spring:
  application:
    name: livegoods-order
  profiles:
    active: mongodb
server:
  port: 9009
eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.137:8761/eureka/
  instance:
    prefer-ip-address: true # 优选IP作为服务的注册、发现、访问地址。